### ISSUE TITLE
Would love to contribute to adding the opposite to this project (AR => Franco)!

### ISSUE THREAD

**Issue by anthonyyoussef01** [popcar2/Franco_AHK#1]

**Comment by popcar2** [comment]
The script is MIT licensed so feel free to contribute. It probably won't be too hard since you'll just reverse everything in the current script (ش --> sh instead of sh --> ش)

**Comment by anthonyyoussef01** [comment]
#2

**Comment by anthonyyoussef01** [comment]
Thank you
